Dependabot のプルリクエストを自動マージする GitHub Actions のワークフローを実装
osdev-jp/osdev-jp.github.io pull request #23
Opened 2023-11-26 10:36 UTC by Takym

* <https://github.com/osdev-jp/osdev-jp.github.io/pull/6#issuecomment-1826530618> に関連します。
    * 今までは、Dependabot が作成したプルリクエストを人間が検証してからマージする仕組みにしていました。
* Dependabot がプルリクエストを作成すると、自動的に `master` へマージする GitHub Actions のワークフローを実装しました。
    * <https://github.com/Takym/osdev-jp> では正常に動作しましたが、この PR をマージする前に再度検証する必要があると思います。
    * <https://github.com/Takym/osdev-jp/actions/runs/6994928862> によって <https://github.com/Takym/osdev-jp/pull/3> がマージされました。
    * <https://github.com/Takym/osdev-jp/pull/4> は、ワークフローの起動条件に合致しないので、マージされません。
    * Wiki が更新されると、<https://github.com/Takym/osdev-jp> の Dependabot が反応して PR を作成し、自動的に <https://github.com/Takym/osdev-jp/tree/master> へマージされます。
        * （このリポジトリではなくフォークで動作します。）
* Dependabot の更新頻度を日毎に変更しました。
* ローカル環境で Jekyll を用いてビルドする為のスクリプトを追加しました。

## TODO
* [ ] ワークフローの安全性を検証する。

2023-11-26 10:44 UTC, Takym commented on .github/workflows/MergeDependabotPR.yml
> +       contents: write
TODO: 権限を適切に設定する。
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

2024-02-24 13:17 UTC, Takym commented on .github/workflows/MergeDependabotPR.yml
> +    - uses: KeisukeYamashita/auto-pull-request-merge@v1
TODO: 安全性を確かめる。

2024-05-28 20:27 UTC, Takym commented on .github/workflows/MergeDependabotPR.yml
> +    - uses: KeisukeYamashita/auto-pull-request-merge@v1
<https://github.com/KeisukeYamashita/auto-pull-request-merge> からフォークして管理を行うという選択肢もあります。

2024-05-28 20:29 UTC, Takym commented on .github/dependabot.yml
> -      interval: "monthly"
自動マージを行うのであれば、Dependabot を毎日動かしても問題ないでしょう。

2024-09-02 11:43 UTC, Takym reviewed
マージする前に確認しておくべき事項は三つあります。

2024-09-09 12:14 UTC, Takym commented
* [仕組み解説ページ (GitHub Wiki)](https://github.com/osdev-jp/osdev-jp.github.io/wiki/Takym-WikiToPages)
* [仕組み解説ページ (GitHub Pages)](https://osdev.jp/wiki/Takym-WikiToPages)

2025-07-15 11:51 UTC, Takym commented on .github/workflows/MergeDependabotPR.yml
> +    - uses: KeisukeYamashita/auto-pull-request-merge@v1
上手くブランチを特定できれば `git merge` コマンドでマージできるかもしれません。

2025-07-15 12:22 UTC, Takym commented on .github/dependabot.yml
> -      interval: "monthly"
Dependabot を使わずに GitHub Workflow を自動実行する様に書き換えましたが、保険として Dependabot 設定も残しておきます。

2025-07-15 12:35 UTC, Takym commented
外部ツール（https://github.com/KeisukeYamashita/auto-pull-request-merge）を使わない方が安全と考え、ワークフローを定期的に実行する方式に変更しました。保険として Dependabot の設定も残してあります。

詳しくは https://github.com/osdev-jp/osdev-jp.github.io/wiki/Takym-WikiToPages をご参照ください。

2025-07-15 12:54 UTC, Takym commented
このプルリクエストはコミット数が多いので、コミット履歴を読み易くするという目的で、「Squash and merge」を選ぶ事を推奨します。「Merge pull request」の右側にある「▼」を押下するとメニューが表示される筈です。
<img width="595" height="444" alt="image" src="https://github.com/user-attachments/assets/a482a6a1-f385-405a-ac85-86d680820aff" />

2026-03-05 01:37 UTC, Takym commented
[このコメント](#issuecomment-3073490099)でも述べましたが、このプルリクエストは Squash した方が良いかと思います。80 コミットもありますが、殆どが自動マージの検証の為のコミットです。コミットを一つにまとめてしまっても、詳細な履歴はこのプルリクエストからいつでも確認できます。

2026-08-03 11:40 UTC, TaiseiIto requested changes
PRありがとうございます！
一応こちらでもforkして検証してみて，大丈夫そうであればマージします．

2026-08-03 11:40 UTC, TaiseiIto commented on README.md
> +[![Update Wiki Submodule](https://github.com/osdev-jp/osdev-jp.github.io/actions/workflows/UpdateWikiSubmodule.yml/badge.svg)](https://github.com/osdev-jp/osdev-jp.github.io/actions/workflows/UpdateW
ステータスバッジは閲覧者にとってはあまり意味がないと思うので削除するか下の方の目立たない場所に移動する方がいいと思います．

2026-08-03 23:37 UTC, Takym commented
https://github.com/TaiseiIto/osdev-jp では既定のブランチが [`landing`](https://github.com/TaiseiIto/osdev-jp/tree/landing) になっている様です。[`master`](https://github.com/TaiseiIto/osdev-jp/tree/master) を既定のブランチに設定しない限りは、ワークフローは動作しませんので、ご確認お願い致します。

2026-08-03 23:56 UTC, Takym commented on README.md
> +[![Update Wiki Submodule](https://github.com/osdev-jp/osdev-jp.github.io/actions/workflows/UpdateWikiSubmodule.yml/badge.svg)](https://github.com/osdev-jp/osdev-jp.github.io/actions/workflows/UpdateW
https://github.com/Takym/osdev-jp/commit/f66fb245fe7211e149483b864b7ef1359ec565ad / https://github.com/Takym/osdev-jp/commit/7a5337d4840a9bf3713e53ed49d332a1a8d66b79
ウィキへのリンクの部分へ移動しました。併せて、ステータスバッジで失敗と表示されている時に、Issues か「運営の相談」チャンネルに連絡して欲しい旨を入れました。確かに、何も説明無しにステータスバッジのみを表示するのは、閲覧者を混乱させてしまいますので。

2026-08-03 23:58 UTC, Takym commented on .github/workflows/UpdateWikiSubmodule.yml
> +    branches: [ master ]
こちら Dependabot がプルリクエストを作成した時に自動実行させる為の記述ですが、それ以外のプルリクエストでも動作してしまいます。現在は頻繁にプルリクエストが作成されている訳ではなく、特に問題は無いと思いますが、念のため、ご確認いただけると幸いです。

2026-08-04 00:01 UTC, Takym commented on .github/workflows/UpdateWikiSubmodule.yml
> +    branches: [ master ]
ウィキの更新以外に、「actions/checkout@v6」の更新を Dependabot が通知する時にもワークフローが呼び出されてしまいます。

削除用：
```suggestion
```

2026-08-04 00:10 UTC, Takym commented on .github/workflows/UpdateWikiSubmodule.yml
> +          git commit -m "[BOT] Update Wiki Submodule to the Current Latest version" || exit $(($? - 1))
コミットメッセージは日本語化した方が良いかもしれないと思いましたが、如何でしょうか。
```suggestion
          git config --local user.email "action@github.com"
      - name: "Commit & Push"
        run: |
          git add wiki
          git commit -m "【自動実行】ウィキを最新版へ更新" || exit $(($? - 1))
```
https://github.com/actions/checkout/issues/13#issuecomment-724415212 によると、メールアドレスは「action@github.com」の方が良いかもしれません。

2026-08-04 00:12 UTC, Takym reviewed
幾つか自分でソースコードにコメントを追加しました。

2026-08-04 09:53 UTC, TaiseiIto commented on README.md
> +[![Update Wiki Submodule](https://github.com/osdev-jp/osdev-jp.github.io/actions/workflows/UpdateWikiSubmodule.yml/badge.svg)](https://github.com/osdev-jp/osdev-jp.github.io/actions/workflows/UpdateW
OKです！

2026-08-04 10:04 UTC, TaiseiIto commented on .github/workflows/UpdateWikiSubmodule.yml
> +          git commit -m "[BOT] Update Wiki Submodule to the Current Latest version" || exit $(($? - 1))
コミットメッセージが英語で困るということはないので，英語でいいと思います．
メールアドレスの変更だけお願いします．

2026-08-04 10:13 UTC, TaiseiIto commented on .github/workflows/UpdateWikiSubmodule.yml
> +    branches: [ master ]
プルリクの頻度的に問題にはならないと思うので，削除しなくても大丈夫です．

2026-08-05 15:15 UTC, Takym commented on .github/workflows/UpdateWikiSubmodule.yml
> +          git commit -m "[BOT] Update Wiki Submodule to the Current Latest version" || exit $(($? - 1))
申し訳ございません。メールアドレスの件について、https://github.com/actions/checkout/issues/13#issuecomment-724415212 のコメントを誤読しておりました。当該コメントのスクリーンショット画像では、`action@github.com` に設定するとアカウント名の部分が https://github.com/actions-user へリンクされている様に見えるのですが、正しく機能しないと書かれていました。プライベートリポジトリで試してみたところ、上手くリンクしている様に見えましたが。メールアドレスは `noreply@localhost` のままでも動作上は問題ありませんが、どのアカウントへもリンクされなくなります。`noreply@localhost` とすると、アカウント名の部分に任意の文字列を入れる事ができます。

https://github.com/actions/checkout/blob/main/README.md#push-a-commit-using-the-built-in-token によると、以下の様に設定するのが良さそうです：
```suggestion
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: "Commit & Push"
        run: |
          git add wiki
          git commit -m "[BOT] Update Wiki Submodule to the Current Latest version" || exit $(($? - 1))
```

（尚、作業を簡単にするという観点では、編集適用ボタンを押すだけですので、メールアドレスの設定を `actions@github.com` にするならば、https://github.com/osdev-jp/osdev-jp.github.io/pull/23#discussion_r3708536106 の提案通りの編集の方が楽だったりします。コミットメッセージを日本語化しても特に困る事はありませんし。）

2026-08-06 09:01 UTC, TaiseiIto commented on .github/workflows/UpdateWikiSubmodule.yml
> +          git commit -m "[BOT] Update Wiki Submodule to the Current Latest version" || exit $(($? - 1))
ありがとうございます．
（なぜか編集適用ボタンがこちらだと表示されていないので，たかやまさんの方で[こちら](https://github.com/osdev-jp/osdev-jp.github.io/pull/23#discussion_r3721765948)の変更の適用をお願いします．）

2026-08-06 09:33 UTC, Takym commented on .github/workflows/UpdateWikiSubmodule.yml
> +          git commit -m "[BOT] Update Wiki Submodule to the Current Latest version" || exit $(($? - 1))
押しました。
（編集適用ボタンは、プルリクエストの作成者にのみ表示されます。）

2026-08-06 20:43 UTC, Takym commented
ワークフローを書き換えましたので、再検証が必要と考え、このプルリクエストはいったん下書きに戻します。

2026-09-08 01:45 UTC, Takym commented
たった今、ワークフローを手動で実行して検証しました（<https://github.com/osdev-jp/osdev-jp.github.io/pull/23/changes/01fa171403fda16377270055f4cea0b10616e710>）。正常に動作している様に思いますので、「Ready for review」（マージ可能）に設定します。

2026-09-22 04:20 UTC, TaiseiIto approved these changes
LGTM

2026-09-22 04:20 UTC, merged